dist: bionic


language: rust

env:
 global:
   - RUST_BACKTRACE=1

rust:
  - nightly

matrix:
  fast_finish: true

before_script:
  - echo "deb http://cz.archive.ubuntu.com/ubuntu disco main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install cmake doxygen xdot
  - sudo apt-get install g++-multilib libc6-dev-i386 gcc-arm-none-eabi libnewlib-arm-none-eabi
  - rustup target add thumbv6m-none-eabi
  - rustup component add rustfmt
  # - rustup component add clippy
  # - rustup component add clippy --toolchain stable-x86_64-unknown-linux-gnu

script:
  - cargo build
  # - cargo build --example stm32l0x2 --features helium_feather
  # - cargo build --example stm32l0x2 --features b_l072z_lrwan1
  # - cargo build --example stm32l0x2 --features catena_4610
  # # - cargo clippy -- -D clippy::all
  - cargo fmt -- --check
